### ISSUE TITLE
Error in running playbook.

### ISSUE THREAD

**Issue by eschabell** [RedHatDemos/CFME_Demo_Builder#1]
$ ansible-playbook cfme_demo_build.yml 
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in '/Users/erics/demo-projects/CFME_Demo_Builder/cfme_demo_build.yml': line 43, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    user: name=root update_password=always password="{{ root_hash }}"
  - name: Add to satellite
    ^ here

**Comment by rut31337** [comment]
removed name fields from blocks
